- name: Install apps
  pip:
    name:
    - docker
    - docker-compose

- name: Git pull
  git:
    dest: "{{ deployment_path }}"
    repo: "{{ git_repository }}"
    version: "{{ git_branch }}"

- name: Docker Compose start
  docker_compose:
    project_src: "{{ deployment_path }}"
    project_name: "pandainfra"
    build: yes
    debug: yes